@ECHO OFF
@echo Iniciando Entorno virtual e instalando dependencias...
@echo Starting virtual environment and Installing dependencies...
powershell python -m venv env; env/Scripts/activate.ps1; pip install -r requirements.txt