# Generated by Django 3.2.7 on 2021-10-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0007_auto_20211009_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(0, 'En Espera'), (1, 'En Preparación'), (2, 'En Ruta'), (3, 'Entregado'), (4, 'Cancelado')], default=0, max_length=20, verbose_name='Order Status'),
        ),
    ]
